Models/Elemento.cs
namespace SuperMercado.Models
{
    public class Elemento
    {
        // para elaborar la compra
        public Producto producto { get; set; }
        public int cantidad { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace SuperMercado.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Producto.cs
namespace SuperMercado.Models
{
    public class Producto
    {
        // productos disponibles
        public int id { get; set; }
        public string nombre { get; set; }
        public double precio { get; set; }
        public string imagen { get; set; }
    }
}

Models/ProductoModel.cs
using System.Collections.Generic;
using System.Linq;

namespace SuperMercado.Models
{
    public class ProductoModel
    {
        //Clase para visualizar en el formulario principal
        private List<Producto> productos;
        public ProductoModel()
        {
            productos = new List<Producto>()
            {
                new Producto
                {
                    id = 1,
                    nombre = "Coca Cola",
                    precio = 5.99,
                    imagen = "cocacola.jpg"
                },
                new Producto
                {
                    id = 2,
                    nombre = "Jabon Liquido",
                    precio = 30.70,
                    imagen = "jabon.jpg"
                },
                new Producto
                {
                    id = 3,
                    nombre = "Papel Higienico",
                    precio = 25.50,
                    imagen = "papel.jpg"
                },
                new Producto
                {
                    id = 4,
                    nombre = "Leche Pil en Tarro",
                    precio = 220.99,
                    imagen = "leche.jpg"
                }
            };
        }
        public List<Producto> getTodo()
        {
           //retorna todos los productos
            return productos;
        }
        public Producto getProducto(int id)
        {
            // retornamos un producto por su id
            return productos.Single(p => p.id == id);
        }
    }
}

Controllers/CarritoController.cs
using Microsoft.AspNetCore.Mvc;
using SuperMercado.Models;
using System.Collections.Generic;
using SuperMercado.Herramientas;
using System;
using System.Linq;

namespace SuperMercado.Controllers
{
    public class CarritoController : Controller
    {
        public IActionResult Index()
        {
            List<Elemento> carrito = Conversor.RecuperarObjeto<List<Elemento>>(HttpContext.Session, "carrito");
           //validacion del carrito
            if (carrito != null && carrito.Count > 0)
            {
                //a viewbag
                ViewBag.carrito = carrito;
                //calculamos total
                ViewBag.total = carrito.Sum(e => e.producto.precio * e.cantidad);
            }
            else
            {
                ViewBag.carrito = new List<Elemento>();
                ViewBag.total = 0;
            }
            return View();
        }

        [Route("Comprar/{id}")]
        public IActionResult Comprar(int id)
        {
            ProductoModel aux = new ProductoModel();//Auxiliar
            //para primer producto
            if (Conversor.RecuperarObjeto<List<Elemento>>(HttpContext.Session, "carrito") == null)
            {
                List<Elemento> carrito = new List<Elemento>();
                carrito.Add(new Elemento { producto = aux.getProducto(id), cantidad = 1 });
                Conversor.GuardarObjeto(HttpContext.Session, "carrito", carrito);
            }
            else
            // en caso de no existir o ser otro producto nuevo
            {
                List<Elemento> carrito = Conversor.RecuperarObjeto<List<Elemento>>(HttpContext.Session, "carrito");
                int indice = existe(id);
                //para aumentar un producto que ya existe
                if (indice != -1)
                    carrito[indice].cantidad++;
               //producto nuevo que no esta en el carrito
                else
                    carrito.Add(new Elemento { producto = aux.getProducto(id), cantidad = 1 });

                Conversor.GuardarObjeto(HttpContext.Session, "carrito", carrito);
            }
            return RedirectToAction("Index");
        }
        [Route("Eliminar/{id}")]
        public IActionResult Eliminar(int id)
        {
            List<Elemento> carrito = Conversor.RecuperarObjeto<List<Elemento>>(HttpContext.Session, "carrito");
            int indice = existe(id);
            if (indice != -1)//existe
            {
                carrito[indice].cantidad--;
                if (carrito[indice].cantidad <= 0)
                    carrito.RemoveAt(indice);
                Conversor.GuardarObjeto(HttpContext.Session, "carrito", carrito);
            }
            return RedirectToAction("Index");
        }
        private int existe(int id)
        {
           //para validar si el producto existe
            List<Elemento> carrito = Conversor.RecuperarObjeto<List<Elemento>>(HttpContext.Session, "carrito");
            for (int i = 0; i < carrito.Count; i++)
            {
                if (carrito[i].producto.id == id)
                    return i;
            }
            return -1;
        }
        public IActionResult Vaciar()
        {
            try
            {
                List<Elemento> carrito = Conversor.RecuperarObjeto<List<Elemento>>(HttpContext.Session, "carrito");
                ViewBag.total = carrito.Sum(e => e.producto.precio * e.cantidad);
                carrito = new List<Elemento>();
                Conversor.GuardarObjeto(HttpContext.Session, "carrito", carrito);
                
            }
            catch (Exception)
            {

               // throw;
            }
            return View("Fin");

        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SuperMercado.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SuperMercado.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SuperController.cs
using Microsoft.AspNetCore.Mvc;
using SuperMercado.Models;

namespace SuperMercado.Controllers
{
    [Route("Super")]
    public class SuperController : Controller
    {
        [Route("")]
        [Route("~/")]
        [Route("index")]
        public IActionResult Index()
        {
            ProductoModel productoModel = new ProductoModel();
            ViewBag.productos = productoModel.getTodo();//pasando a la vista en Viewbag
            return View();
        }
    }
}

Views/Carrito/Fin.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    if(ViewBag.total>0)
    {
    <h3>Compra Realizada!</h3>
    <p>Valor de la compra Bs.@string.Format("{0:0.00}", ViewBag.total)</p>

    }
    else
    {
    <h3>No se agregaron productos al carrito !</h3>
        
    }
   
}
<a class="btn btn-primary" asp-controller="Super" asp-action="index">Página principal</a>

Views/Carrito/Index.cshtml
<h3>Detalle del Carrito
    <div align="right">
        <a class="btn btn-info" asp-controller="Super" asp-action="index">Retornar</a>
    </div>
</h3>
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>Id</th>
            <th>Producto</th>
            <th>Imagen / Eliminar</th>
            <th>Precio Bs.</th>
            <th>Cantidad</th>
            <th>SubTotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Elemento item in ViewBag.carrito)
        {
            <tr>
                <td>@item.producto.id</td>
                <td>@item.producto.nombre</td>
                <td>
                    <img src="~/imagenes/@item.producto.imagen" width="80" height="80"/>
                    <a class="btn btn-danger" asp-controller="Carrito" asp-action="Eliminar" asp-route-id="@item.producto.id">Eliminar un producto</a>
                </td>
                <td>@item.producto.precio</td>
                <td>@item.cantidad</td>
                <td>@string.Format("{0:0.00}", (item.producto.precio * item.cantidad))</td>
            </tr>
        }
        <tr>
            <td colspan="5" align="right"><b>Total Bs.:</b></td>
            <td> <b>@string.Format("{0:0.00}", ViewBag.total)</b></td>
        </tr>
        

    </tbody>
</table>
<a class="btn btn-warning" asp-controller="Carrito" asp-action="Vaciar">Finalizar Compra</a>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SuperMercado</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SuperMercado</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SuperMercado - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Super/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h3>Supermercado
    <div align="right">
        <a class="btn btn-info" asp-controller="Carrito" asp-action="Index">Ver Carrito</a>
    </div>
</h3>
<table class="table" align="center">
    <thead class="thead-dark table">
        <tr>
            <th>Id</th>
            <th>Producto</th>
            <th>Imagen / Compra</th>
            <th>Precio Bs.</th>            
        </tr>
    </thead>
    <tbody>
        @foreach (var prod in ViewBag.productos)
        {
            <tr>
                <td>@prod.id</td>
                <td>@prod.nombre</td>
                <td><img src="~/imagenes/@prod.imagen" width="80" height="80"/>
                    <a class="btn btn-success"  asp-controller="Carrito" asp-action="Comprar" asp-route-id="@prod.id">Agregar</a>
                </td>
                <td>@string.Format("{0:0.00}", prod.precio)</td>
                
            </tr>
        }
    </tbody>
</table>